[package]
edition = "2024"
name    = "win64-macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
syn         = { version = "2.0.x", features = ["full"] }
quote       = "1.0.x"
proc-macro2 = "1.0.x"
convert_case = "0.8.x"