use win64_macro::{GetId, Getter};

use self::{data::MessageData, id::MessageId};

pub mod data;
pub mod id;
pub mod pump;
pub mod thread;

#[derive(Debug, Clone, PartialEq, Eq, Getter, GetId)]
#[getters((raw, MessageData))]
pub enum Message {
  Reserved { id: MessageId, raw: MessageData },
  Other { id: MessageId, raw: MessageData },
  User { id: MessageId, raw: MessageData },
  App { id: MessageId, raw: MessageData },
  Activate { raw: MessageData },
  ActivateApp { raw: MessageData },
  AfxFirst { raw: MessageData },
  AfxLast { raw: MessageData },
  AppCommand { raw: MessageData },
  AskCbFormatName { raw: MessageData },
  CancelJournal { raw: MessageData },
  CancelMode { raw: MessageData },
  CaptureChanged { raw: MessageData },
  ChangeCbChain { raw: MessageData },
  ChangeUiState { raw: MessageData },
  Char { raw: MessageData },
  CharToItem { raw: MessageData },
  ChildActivate { raw: MessageData },
  Clear { raw: MessageData },
  ClipboardUpdate { raw: MessageData },
  Close { raw: MessageData },
  Command { raw: MessageData },
  CommNotify { raw: MessageData },
  Compacting { raw: MessageData },
  CompareItem { raw: MessageData },
  ContextMenu { raw: MessageData },
  Copy { raw: MessageData },
  CopyData { raw: MessageData },
  Create { raw: MessageData },
  CtlColorBtn { raw: MessageData },
  CtlColorDlg { raw: MessageData },
  CtlColorEdit { raw: MessageData },
  CtlColorListBox { raw: MessageData },
  CtlColorMsgBox { raw: MessageData },
  CtlColorScrollBar { raw: MessageData },
  CtlColorStatic { raw: MessageData },
  Cut { raw: MessageData },
  DeadChar { raw: MessageData },
  DeleteItem { raw: MessageData },
  Destroy { raw: MessageData },
  DestroyClipboard { raw: MessageData },
  DeviceChange { raw: MessageData },
  DevModeChange { raw: MessageData },
  DisplayChange { raw: MessageData },
  DpiChanged { raw: MessageData },
  DpiChangedAfterParent { raw: MessageData },
  DpiChangedBeforeParent { raw: MessageData },
  DrawClipboard { raw: MessageData },
  DrawItem { raw: MessageData },
  DropFiles { raw: MessageData },
  DwmColorizationColorChanged { raw: MessageData },
  DwmCompositionChanged { raw: MessageData },
  DwmNcRenderingChanged { raw: MessageData },
  DwmSendIconicLivePreviewBitmap { raw: MessageData },
  DwmSendIconicThumbnail { raw: MessageData },
  DwmWindowMaximizedChange { raw: MessageData },
  Enable { raw: MessageData },
  EndSession { raw: MessageData },
  EnterIdle { raw: MessageData },
  EnterMenuLoop { raw: MessageData },
  EnterSizeMove { raw: MessageData },
  EraseBkgnd { raw: MessageData },
  ExitMenuLoop { raw: MessageData },
  ExitSizeMove { raw: MessageData },
  FontChange { raw: MessageData },
  Gesture { raw: MessageData },
  GestureNotify { raw: MessageData },
  GetDlgCode { raw: MessageData },
  GetDpiScaledSize { raw: MessageData },
  GetFont { raw: MessageData },
  GetHotKey { raw: MessageData },
  GetIcon { raw: MessageData },
  GetMinMaxInfo { raw: MessageData },
  GetObject { raw: MessageData },
  GetText { raw: MessageData },
  GetTextLength { raw: MessageData },
  GetTitleBarInfoEx { raw: MessageData },
  HandheldFirst { raw: MessageData },
  HandheldLast { raw: MessageData },
  Help { raw: MessageData },
  HotKey { raw: MessageData },
  HScroll { raw: MessageData },
  HScrollClipboard { raw: MessageData },
  IconEraseBkgnd { raw: MessageData },
  ImeChar { raw: MessageData },
  ImeComposition { raw: MessageData },
  ImeCompositionFull { raw: MessageData },
  ImeControl { raw: MessageData },
  ImeEndComposition { raw: MessageData },
  ImeKeyDown { raw: MessageData },
  ImeKeyUp { raw: MessageData },
  ImeNotify { raw: MessageData },
  ImeRequest { raw: MessageData },
  ImeSelect { raw: MessageData },
  ImeSetContext { raw: MessageData },
  ImeStartComposition { raw: MessageData },
  InitDialog { raw: MessageData },
  InitMenu { raw: MessageData },
  InitMenuPopup { raw: MessageData },
  Input { raw: MessageData },
  InputLangChange { raw: MessageData },
  InputLangChangeRequest { raw: MessageData },
  InputDeviceChange { raw: MessageData },
  KeyDown { raw: MessageData },
  KeyUp { raw: MessageData },
  KillFocus { raw: MessageData },
  LButtonDblClk { raw: MessageData },
  LButtonDown { raw: MessageData },
  LButtonUp { raw: MessageData },
  MButtonDblClk { raw: MessageData },
  MButtonDown { raw: MessageData },
  MButtonUp { raw: MessageData },
  MdiActivate { raw: MessageData },
  MdiCascade { raw: MessageData },
  MdiCreate { raw: MessageData },
  MdiDestroy { raw: MessageData },
  MdiGetActive { raw: MessageData },
  MdiIconArrange { raw: MessageData },
  MdiMaximize { raw: MessageData },
  MdiNext { raw: MessageData },
  MdiRefreshMenu { raw: MessageData },
  MdiRestore { raw: MessageData },
  MdiSetMenu { raw: MessageData },
  MdiTile { raw: MessageData },
  MeasureItem { raw: MessageData },
  MenuChar { raw: MessageData },
  MenuCommand { raw: MessageData },
  MenuDrag { raw: MessageData },
  MenuGetObject { raw: MessageData },
  MenuRButtonUp { raw: MessageData },
  MenuSelect { raw: MessageData },
  MouseActivate { raw: MessageData },
  MouseHWheel { raw: MessageData },
  MouseMove { raw: MessageData },
  MouseWheel { raw: MessageData },
  Move { raw: MessageData },
  Moving { raw: MessageData },
  NcActivate { raw: MessageData },
  NcCalcSize { raw: MessageData },
  NcCreate { raw: MessageData },
  NcDestroy { raw: MessageData },
  NcHitTest { raw: MessageData },
  NcLButtonDblClk { raw: MessageData },
  NcLButtonDown { raw: MessageData },
  NcLButtonUp { raw: MessageData },
  NcMButtonDblClk { raw: MessageData },
  NcMButtonDown { raw: MessageData },
  NcMButtonUp { raw: MessageData },
  NcMouseHover { raw: MessageData },
  NcMouseLeave { raw: MessageData },
  NcMouseMove { raw: MessageData },
  NcPaint { raw: MessageData },
  NcPointerDown { raw: MessageData },
  NcPointerUp { raw: MessageData },
  NcPointerUpdate { raw: MessageData },
  NcRButtonDblClk { raw: MessageData },
  NcRButtonDown { raw: MessageData },
  NcRButtonUp { raw: MessageData },
  NcXButtonDblClk { raw: MessageData },
  NcXButtonDown { raw: MessageData },
  NcXButtonUp { raw: MessageData },
  NextDlgCtl { raw: MessageData },
  NextMenu { raw: MessageData },
  Notify { raw: MessageData },
  NotifyFormat { raw: MessageData },
  Null { raw: MessageData },
  Paint { raw: MessageData },
  PaintClipboard { raw: MessageData },
  PaintIcon { raw: MessageData },
  PaletteChanged { raw: MessageData },
  PaletteIsChanging { raw: MessageData },
  ParentNotify { raw: MessageData },
  Paste { raw: MessageData },
  PenWinFirst { raw: MessageData },
  PenWinLast { raw: MessageData },
  PointerActivate { raw: MessageData },
  PointerCaptureChanged { raw: MessageData },
  PointerDeviceChange { raw: MessageData },
  PointerDeviceInRange { raw: MessageData },
  PointerDeviceOutOfRange { raw: MessageData },
  PointerDown { raw: MessageData },
  PointerEnter { raw: MessageData },
  PointerHWheel { raw: MessageData },
  PointerLeave { raw: MessageData },
  PointerRoutedAway { raw: MessageData },
  PointerRoutedReleased { raw: MessageData },
  PointerRoutedTo { raw: MessageData },
  PointerUp { raw: MessageData },
  PointerUpdate { raw: MessageData },
  PointerWheel { raw: MessageData },
  Power { raw: MessageData },
  PowerBroadcast { raw: MessageData },
  Print { raw: MessageData },
  PrintClient { raw: MessageData },
  QueryDragIcon { raw: MessageData },
  QueryEndSession { raw: MessageData },
  QueryNewPalette { raw: MessageData },
  QueryOpen { raw: MessageData },
  QueryUiState { raw: MessageData },
  QueueSync { raw: MessageData },
  Quit { raw: MessageData },
  RButtonDblClk { raw: MessageData },
  RButtonDown { raw: MessageData },
  RButtonUp { raw: MessageData },
  RenderAllFormats { raw: MessageData },
  RenderFormat { raw: MessageData },
  SetCursor { raw: MessageData },
  SetFocus { raw: MessageData },
  SetFont { raw: MessageData },
  SetHotKey { raw: MessageData },
  SetIcon { raw: MessageData },
  SetRedraw { raw: MessageData },
  SetText { raw: MessageData },
  SettingChange { raw: MessageData },
  ShowWindow { raw: MessageData },
  Size { raw: MessageData },
  SizeClipboard { raw: MessageData },
  Sizing { raw: MessageData },
  SpoolerStatus { raw: MessageData },
  StyleChanged { raw: MessageData },
  StyleChanging { raw: MessageData },
  SyncPaint { raw: MessageData },
  SysChar { raw: MessageData },
  SysColorChange { raw: MessageData },
  SysCommand { raw: MessageData },
  SysDeadChar { raw: MessageData },
  SysKeyDown { raw: MessageData },
  SysKeyUp { raw: MessageData },
  TabletFirst { raw: MessageData },
  TabletLast { raw: MessageData },
  TCard { raw: MessageData },
  ThemeChanged { raw: MessageData },
  TimeChange { raw: MessageData },
  Timer { raw: MessageData },
  TooltipDismiss { raw: MessageData },
  Touch { raw: MessageData },
  TouchHitTesting { raw: MessageData },
  Undo { raw: MessageData },
  UniChar { raw: MessageData },
  UninitMenuPopup { raw: MessageData },
  UpdateUiState { raw: MessageData },
  UserChanged { raw: MessageData },
  VKeyToItem { raw: MessageData },
  VScroll { raw: MessageData },
  VScrollClipboard { raw: MessageData },
  WindowPosChanged { raw: MessageData },
  WindowPosChanging { raw: MessageData },
  WtsSessionChange { raw: MessageData },
  XButtonDblClk { raw: MessageData },
  XButtonDown { raw: MessageData },
  XButtonUp { raw: MessageData },
}

impl Message {
  pub const fn is_key(&self) -> bool {
    self.id().is_key()
  }

  pub const fn is_mouse(&self) -> bool {
    self.id().is_mouse()
  }

  pub fn from_raw(msg: MessageId, raw: MessageData) -> Self {
    match msg {
      MessageId::Reserved(_) => Self::Reserved { id: msg, raw },
      MessageId::Activate => Self::Activate { raw },
      MessageId::ActivateApp => Self::ActivateApp { raw },
      MessageId::AfxFirst => Self::AfxFirst { raw },
      MessageId::AfxLast => Self::AfxLast { raw },
      MessageId::App(_) => Self::App { id: msg, raw },
      MessageId::AppCommand => Self::AppCommand { raw },
      MessageId::AskCbFormatName => Self::AskCbFormatName { raw },
      MessageId::CancelJournal => Self::CancelJournal { raw },
      MessageId::CancelMode => Self::CancelMode { raw },
      MessageId::CaptureChanged => Self::CaptureChanged { raw },
      MessageId::ChangeCbChain => Self::ChangeCbChain { raw },
      MessageId::ChangeUiState => Self::ChangeUiState { raw },
      MessageId::Char => Self::Char { raw },
      MessageId::CharToItem => Self::CharToItem { raw },
      MessageId::ChildActivate => Self::ChildActivate { raw },
      MessageId::Clear => Self::Clear { raw },
      MessageId::ClipboardUpdate => Self::ClipboardUpdate { raw },
      MessageId::Close => Self::Close { raw },
      MessageId::Command => Self::Command { raw },
      MessageId::CommNotify => Self::CommNotify { raw },
      MessageId::Compacting => Self::Compacting { raw },
      MessageId::CompareItem => Self::CompareItem { raw },
      MessageId::ContextMenu => Self::ContextMenu { raw },
      MessageId::Copy => Self::Copy { raw },
      MessageId::CopyData => Self::CopyData { raw },
      MessageId::Create => Self::Create { raw },
      MessageId::CtlColorBtn => Self::CtlColorBtn { raw },
      MessageId::CtlColorDlg => Self::CtlColorDlg { raw },
      MessageId::CtlColorEdit => Self::CtlColorEdit { raw },
      MessageId::CtlColorListBox => Self::CtlColorListBox { raw },
      MessageId::CtlColorMsgBox => Self::CtlColorMsgBox { raw },
      MessageId::CtlColorScrollBar => Self::CtlColorScrollBar { raw },
      MessageId::CtlColorStatic => Self::CtlColorStatic { raw },
      MessageId::Cut => Self::Cut { raw },
      MessageId::DeadChar => Self::DeadChar { raw },
      MessageId::DeleteItem => Self::DeleteItem { raw },
      MessageId::Destroy => Self::Destroy { raw },
      MessageId::DestroyClipboard => Self::DestroyClipboard { raw },
      MessageId::DeviceChange => Self::DeviceChange { raw },
      MessageId::DevModeChange => Self::DevModeChange { raw },
      MessageId::DisplayChange => Self::DisplayChange { raw },
      MessageId::DpiChanged => Self::DpiChanged { raw },
      MessageId::DpiChangedAfterParent => Self::DpiChangedAfterParent { raw },
      MessageId::DpiChangedBeforeParent => Self::DpiChangedBeforeParent { raw },
      MessageId::DrawClipboard => Self::DrawClipboard { raw },
      MessageId::DrawItem => Self::DrawItem { raw },
      MessageId::DropFiles => Self::DropFiles { raw },
      MessageId::DwmColorizationColorChanged => Self::DwmColorizationColorChanged { raw },
      MessageId::DwmCompositionChanged => Self::DwmCompositionChanged { raw },
      MessageId::DwmNcRenderingChanged => Self::DwmNcRenderingChanged { raw },
      MessageId::DwmSendIconicLivePreviewBitmap => Self::DwmSendIconicLivePreviewBitmap { raw },
      MessageId::DwmSendIconicThumbnail => Self::DwmSendIconicThumbnail { raw },
      MessageId::DwmWindowMaximizedChange => Self::DwmWindowMaximizedChange { raw },
      MessageId::Enable => Self::Enable { raw },
      MessageId::EndSession => Self::EndSession { raw },
      MessageId::EnterIdle => Self::EnterIdle { raw },
      MessageId::EnterMenuLoop => Self::EnterMenuLoop { raw },
      MessageId::EnterSizeMove => Self::EnterSizeMove { raw },
      MessageId::EraseBkgnd => Self::EraseBkgnd { raw },
      MessageId::ExitMenuLoop => Self::ExitMenuLoop { raw },
      MessageId::ExitSizeMove => Self::ExitSizeMove { raw },
      MessageId::FontChange => Self::FontChange { raw },
      MessageId::Gesture => Self::Gesture { raw },
      MessageId::GestureNotify => Self::GestureNotify { raw },
      MessageId::GetDlgCode => Self::GetDlgCode { raw },
      MessageId::GetDpiScaledSize => Self::GetDpiScaledSize { raw },
      MessageId::GetFont => Self::GetFont { raw },
      MessageId::GetHotKey => Self::GetHotKey { raw },
      MessageId::GetIcon => Self::GetIcon { raw },
      MessageId::GetMinMaxInfo => Self::GetMinMaxInfo { raw },
      MessageId::GetObject => Self::GetObject { raw },
      MessageId::GetText => Self::GetText { raw },
      MessageId::GetTextLength => Self::GetTextLength { raw },
      MessageId::GetTitleBarInfoEx => Self::GetTitleBarInfoEx { raw },
      MessageId::HandheldFirst => Self::HandheldFirst { raw },
      MessageId::HandheldLast => Self::HandheldLast { raw },
      MessageId::Help => Self::Help { raw },
      MessageId::HotKey => Self::HotKey { raw },
      MessageId::HScroll => Self::HScroll { raw },
      MessageId::HScrollClipboard => Self::HScrollClipboard { raw },
      MessageId::IconEraseBkgnd => Self::IconEraseBkgnd { raw },
      MessageId::ImeChar => Self::ImeChar { raw },
      MessageId::ImeComposition => Self::ImeComposition { raw },
      MessageId::ImeCompositionFull => Self::ImeCompositionFull { raw },
      MessageId::ImeControl => Self::ImeControl { raw },
      MessageId::ImeEndComposition => Self::ImeEndComposition { raw },
      MessageId::ImeKeyDown => Self::ImeKeyDown { raw },
      MessageId::ImeKeyUp => Self::ImeKeyUp { raw },
      MessageId::ImeNotify => Self::ImeNotify { raw },
      MessageId::ImeRequest => Self::ImeRequest { raw },
      MessageId::ImeSelect => Self::ImeSelect { raw },
      MessageId::ImeSetContext => Self::ImeSetContext { raw },
      MessageId::ImeStartComposition => Self::ImeStartComposition { raw },
      MessageId::InitDialog => Self::InitDialog { raw },
      MessageId::InitMenu => Self::InitMenu { raw },
      MessageId::InitMenuPopup => Self::InitMenuPopup { raw },
      MessageId::Input => Self::Input { raw },
      MessageId::InputLangChange => Self::InputLangChange { raw },
      MessageId::InputLangChangeRequest => Self::InputLangChangeRequest { raw },
      MessageId::InputDeviceChange => Self::InputDeviceChange { raw },
      MessageId::KeyDown => Self::KeyDown { raw },
      MessageId::KeyUp => Self::KeyUp { raw },
      MessageId::KillFocus => Self::KillFocus { raw },
      MessageId::LButtonDblClk => Self::LButtonDblClk { raw },
      MessageId::LButtonDown => Self::LButtonDown { raw },
      MessageId::LButtonUp => Self::LButtonUp { raw },
      MessageId::MButtonDblClk => Self::MButtonDblClk { raw },
      MessageId::MButtonDown => Self::MButtonDown { raw },
      MessageId::MButtonUp => Self::MButtonUp { raw },
      MessageId::MdiActivate => Self::MdiActivate { raw },
      MessageId::MdiCascade => Self::MdiCascade { raw },
      MessageId::MdiCreate => Self::MdiCreate { raw },
      MessageId::MdiDestroy => Self::MdiDestroy { raw },
      MessageId::MdiGetActive => Self::MdiGetActive { raw },
      MessageId::MdiIconArrange => Self::MdiIconArrange { raw },
      MessageId::MdiMaximize => Self::MdiMaximize { raw },
      MessageId::MdiNext => Self::MdiNext { raw },
      MessageId::MdiRefreshMenu => Self::MdiRefreshMenu { raw },
      MessageId::MdiRestore => Self::MdiRestore { raw },
      MessageId::MdiSetMenu => Self::MdiSetMenu { raw },
      MessageId::MdiTile => Self::MdiTile { raw },
      MessageId::MeasureItem => Self::MeasureItem { raw },
      MessageId::MenuChar => Self::MenuChar { raw },
      MessageId::MenuCommand => Self::MenuCommand { raw },
      MessageId::MenuDrag => Self::MenuDrag { raw },
      MessageId::MenuGetObject => Self::MenuGetObject { raw },
      MessageId::MenuRButtonUp => Self::MenuRButtonUp { raw },
      MessageId::MenuSelect => Self::MenuSelect { raw },
      MessageId::MouseActivate => Self::MouseActivate { raw },
      MessageId::MouseHWheel => Self::MouseHWheel { raw },
      MessageId::MouseMove => Self::MouseMove { raw },
      MessageId::MouseWheel => Self::MouseWheel { raw },
      MessageId::Move => Self::Move { raw },
      MessageId::Moving => Self::Moving { raw },
      MessageId::NcActivate => Self::NcActivate { raw },
      MessageId::NcCalcSize => Self::NcCalcSize { raw },
      MessageId::NcCreate => Self::NcCreate { raw },
      MessageId::NcDestroy => Self::NcDestroy { raw },
      MessageId::NcHitTest => Self::NcHitTest { raw },
      MessageId::NcLButtonDblClk => Self::NcLButtonDblClk { raw },
      MessageId::NcLButtonDown => Self::NcLButtonDown { raw },
      MessageId::NcLButtonUp => Self::NcLButtonUp { raw },
      MessageId::NcMButtonDblClk => Self::NcMButtonDblClk { raw },
      MessageId::NcMButtonDown => Self::NcMButtonDown { raw },
      MessageId::NcMButtonUp => Self::NcMButtonUp { raw },
      MessageId::NcMouseHover => Self::NcMouseHover { raw },
      MessageId::NcMouseLeave => Self::NcMouseLeave { raw },
      MessageId::NcMouseMove => Self::NcMouseMove { raw },
      MessageId::NcPaint => Self::NcPaint { raw },
      MessageId::NcPointerDown => Self::NcPointerDown { raw },
      MessageId::NcPointerUp => Self::NcPointerUp { raw },
      MessageId::NcPointerUpdate => Self::NcPointerUpdate { raw },
      MessageId::NcRButtonDblClk => Self::NcRButtonDblClk { raw },
      MessageId::NcRButtonDown => Self::NcRButtonDown { raw },
      MessageId::NcRButtonUp => Self::NcRButtonUp { raw },
      MessageId::NcXButtonDblClk => Self::NcXButtonDblClk { raw },
      MessageId::NcXButtonDown => Self::NcXButtonDown { raw },
      MessageId::NcXButtonUp => Self::NcXButtonUp { raw },
      MessageId::NextDlgCtl => Self::NextDlgCtl { raw },
      MessageId::NextMenu => Self::NextMenu { raw },
      MessageId::Notify => Self::Notify { raw },
      MessageId::NotifyFormat => Self::NotifyFormat { raw },
      MessageId::Null => Self::Null { raw },
      MessageId::Paint => Self::Paint { raw },
      MessageId::PaintClipboard => Self::PaintClipboard { raw },
      MessageId::PaintIcon => Self::PaintIcon { raw },
      MessageId::PaletteChanged => Self::PaletteChanged { raw },
      MessageId::PaletteIsChanging => Self::PaletteIsChanging { raw },
      MessageId::ParentNotify => Self::ParentNotify { raw },
      MessageId::Paste => Self::Paste { raw },
      MessageId::PenWinFirst => Self::PenWinFirst { raw },
      MessageId::PenWinLast => Self::PenWinLast { raw },
      MessageId::PointerActivate => Self::PointerActivate { raw },
      MessageId::PointerCaptureChanged => Self::PointerCaptureChanged { raw },
      MessageId::PointerDeviceChange => Self::PointerDeviceChange { raw },
      MessageId::PointerDeviceInRange => Self::PointerDeviceInRange { raw },
      MessageId::PointerDeviceOutOfRange => Self::PointerDeviceOutOfRange { raw },
      MessageId::PointerDown => Self::PointerDown { raw },
      MessageId::PointerEnter => Self::PointerEnter { raw },
      MessageId::PointerHWheel => Self::PointerHWheel { raw },
      MessageId::PointerLeave => Self::PointerLeave { raw },
      MessageId::PointerRoutedAway => Self::PointerRoutedAway { raw },
      MessageId::PointerRoutedReleased => Self::PointerRoutedReleased { raw },
      MessageId::PointerRoutedTo => Self::PointerRoutedTo { raw },
      MessageId::PointerUp => Self::PointerUp { raw },
      MessageId::PointerUpdate => Self::PointerUpdate { raw },
      MessageId::PointerWheel => Self::PointerWheel { raw },
      MessageId::Power => Self::Power { raw },
      MessageId::PowerBroadcast => Self::PowerBroadcast { raw },
      MessageId::Print => Self::Print { raw },
      MessageId::PrintClient => Self::PrintClient { raw },
      MessageId::QueryDragIcon => Self::QueryDragIcon { raw },
      MessageId::QueryEndSession => Self::QueryEndSession { raw },
      MessageId::QueryNewPalette => Self::QueryNewPalette { raw },
      MessageId::QueryOpen => Self::QueryOpen { raw },
      MessageId::QueryUiState => Self::QueryUiState { raw },
      MessageId::QueueSync => Self::QueueSync { raw },
      MessageId::Quit => Self::Quit { raw },
      MessageId::RButtonDblClk => Self::RButtonDblClk { raw },
      MessageId::RButtonDown => Self::RButtonDown { raw },
      MessageId::RButtonUp => Self::RButtonUp { raw },
      MessageId::RenderAllFormats => Self::RenderAllFormats { raw },
      MessageId::RenderFormat => Self::RenderFormat { raw },
      MessageId::SetCursor => Self::SetCursor { raw },
      MessageId::SetFocus => Self::SetFocus { raw },
      MessageId::SetFont => Self::SetFont { raw },
      MessageId::SetHotKey => Self::SetHotKey { raw },
      MessageId::SetIcon => Self::SetIcon { raw },
      MessageId::SetRedraw => Self::SetRedraw { raw },
      MessageId::SetText => Self::SetText { raw },
      MessageId::SettingChange => Self::SettingChange { raw },
      MessageId::ShowWindow => Self::ShowWindow { raw },
      MessageId::Size => Self::Size { raw },
      MessageId::SizeClipboard => Self::SizeClipboard { raw },
      MessageId::Sizing => Self::Sizing { raw },
      MessageId::SpoolerStatus => Self::SpoolerStatus { raw },
      MessageId::StyleChanged => Self::StyleChanged { raw },
      MessageId::StyleChanging => Self::StyleChanging { raw },
      MessageId::SyncPaint => Self::SyncPaint { raw },
      MessageId::SysChar => Self::SysChar { raw },
      MessageId::SysColorChange => Self::SysColorChange { raw },
      MessageId::SysCommand => Self::SysCommand { raw },
      MessageId::SysDeadChar => Self::SysDeadChar { raw },
      MessageId::SysKeyDown => Self::SysKeyDown { raw },
      MessageId::SysKeyUp => Self::SysKeyUp { raw },
      MessageId::TabletFirst => Self::TabletFirst { raw },
      MessageId::TabletLast => Self::TabletLast { raw },
      MessageId::TCard => Self::TCard { raw },
      MessageId::ThemeChanged => Self::ThemeChanged { raw },
      MessageId::TimeChange => Self::TimeChange { raw },
      MessageId::Timer => Self::Timer { raw },
      MessageId::TooltipDismiss => Self::TooltipDismiss { raw },
      MessageId::Touch => Self::Touch { raw },
      MessageId::TouchHitTesting => Self::TouchHitTesting { raw },
      MessageId::Undo => Self::Undo { raw },
      MessageId::UniChar => Self::UniChar { raw },
      MessageId::UninitMenuPopup => Self::UninitMenuPopup { raw },
      MessageId::UpdateUiState => Self::UpdateUiState { raw },
      MessageId::User(_) => Self::User { id: msg, raw },
      MessageId::UserChanged => Self::UserChanged { raw },
      MessageId::VKeyToItem => Self::VKeyToItem { raw },
      MessageId::VScroll => Self::VScroll { raw },
      MessageId::VScrollClipboard => Self::VScrollClipboard { raw },
      MessageId::WindowPosChanged => Self::WindowPosChanged { raw },
      MessageId::WindowPosChanging => Self::WindowPosChanging { raw },
      MessageId::WtsSessionChange => Self::WtsSessionChange { raw },
      MessageId::XButtonDblClk => Self::XButtonDblClk { raw },
      MessageId::XButtonDown => Self::XButtonDown { raw },
      MessageId::XButtonUp => Self::XButtonUp { raw },
      MessageId::Other(_) => Self::Other { id: msg, raw },
    }
  }
}
