use win64_macro::Id;
use windows::Win32::UI::WindowsAndMessaging;

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Id)]
pub enum MessageId {
  Other(u32),
  #[id(WindowsAndMessaging::WM_ACTIVATE)]
  Activate,
  #[id(WindowsAndMessaging::WM_ACTIVATEAPP)]
  ActivateApp,
  #[id(WindowsAndMessaging::WM_AFXFIRST)]
  AfxFirst,
  #[id(WindowsAndMessaging::WM_AFXLAST)]
  AfxLast,
  #[id(WindowsAndMessaging::WM_APP)]
  App,
  #[id(WindowsAndMessaging::WM_APPCOMMAND)]
  AppCommand,
  #[id(WindowsAndMessaging::WM_ASKCBFORMATNAME)]
  AskCbFormatName,
  #[id(WindowsAndMessaging::WM_CANCELJOURNAL)]
  CancelJournal,
  #[id(WindowsAndMessaging::WM_CANCELMODE)]
  CancelMode,
  #[id(WindowsAndMessaging::WM_CAPTURECHANGED)]
  CaptureChanged,
  #[id(WindowsAndMessaging::WM_CHANGECBCHAIN)]
  ChangeCbChain,
  #[id(WindowsAndMessaging::WM_CHANGEUISTATE)]
  ChangeUiState,
  #[id(WindowsAndMessaging::WM_CHAR)]
  Char,
  #[id(WindowsAndMessaging::WM_CHARTOITEM)]
  CharToItem,
  #[id(WindowsAndMessaging::WM_CHILDACTIVATE)]
  ChildActivate,
  #[id(WindowsAndMessaging::WM_CLEAR)]
  Clear,
  #[id(WindowsAndMessaging::WM_CLIPBOARDUPDATE)]
  ClipboardUpdate,
  #[id(WindowsAndMessaging::WM_CLOSE)]
  Close,
  #[id(WindowsAndMessaging::WM_COMMAND)]
  Command,
  #[id(WindowsAndMessaging::WM_COMMNOTIFY)]
  CommNotify,
  #[id(WindowsAndMessaging::WM_COMPACTING)]
  Compacting,
  #[id(WindowsAndMessaging::WM_COMPAREITEM)]
  CompareItem,
  #[id(WindowsAndMessaging::WM_CONTEXTMENU)]
  ContextMenu,
  #[id(WindowsAndMessaging::WM_COPY)]
  Copy,
  #[id(WindowsAndMessaging::WM_COPYDATA)]
  CopyData,
  #[id(WindowsAndMessaging::WM_CREATE)]
  Create,
  #[id(WindowsAndMessaging::WM_CTLCOLORBTN)]
  CtlColorBtn,
  #[id(WindowsAndMessaging::WM_CTLCOLORDLG)]
  CtlColorDlg,
  #[id(WindowsAndMessaging::WM_CTLCOLOREDIT)]
  CtlColorEdit,
  #[id(WindowsAndMessaging::WM_CTLCOLORLISTBOX)]
  CtlColorListBox,
  #[id(WindowsAndMessaging::WM_CTLCOLORMSGBOX)]
  CtlColorMsgBox,
  #[id(WindowsAndMessaging::WM_CTLCOLORSCROLLBAR)]
  CtlColorScrollBar,
  #[id(WindowsAndMessaging::WM_CTLCOLORSTATIC)]
  CtlColorStatic,
  #[id(WindowsAndMessaging::WM_CUT)]
  Cut,
  #[id(WindowsAndMessaging::WM_DEADCHAR)]
  DeadChar,
  #[id(WindowsAndMessaging::WM_DELETEITEM)]
  DeleteItem,
  #[id(WindowsAndMessaging::WM_DESTROY)]
  Destroy,
  #[id(WindowsAndMessaging::WM_DESTROYCLIPBOARD)]
  DestroyClipboard,
  #[id(WindowsAndMessaging::WM_DEVICECHANGE)]
  DeviceChange,
  #[id(WindowsAndMessaging::WM_DEVMODECHANGE)]
  DevModeChange,
  #[id(WindowsAndMessaging::WM_DISPLAYCHANGE)]
  DisplayChange,
  #[id(WindowsAndMessaging::WM_DPICHANGED)]
  DpiChanged,
  #[id(WindowsAndMessaging::WM_DPICHANGED_AFTERPARENT)]
  DpiChangedAfterParent,
  #[id(WindowsAndMessaging::WM_DPICHANGED_BEFOREPARENT)]
  DpiChangedBeforeParent,
  #[id(WindowsAndMessaging::WM_DRAWCLIPBOARD)]
  DrawClipboard,
  #[id(WindowsAndMessaging::WM_DRAWITEM)]
  DrawItem,
  #[id(WindowsAndMessaging::WM_DROPFILES)]
  DropFiles,
  #[id(WindowsAndMessaging::WM_DWMCOLORIZATIONCOLORCHANGED)]
  DwmColorizationColorChanged,
  #[id(WindowsAndMessaging::WM_DWMCOMPOSITIONCHANGED)]
  DwmCompositionChanged,
  #[id(WindowsAndMessaging::WM_DWMNCRENDERINGCHANGED)]
  DwmNcRenderingChanged,
  #[id(WindowsAndMessaging::WM_DWMSENDICONICLIVEPREVIEWBITMAP)]
  DwmSendIconicLivePreviewBitmap,
  #[id(WindowsAndMessaging::WM_DWMSENDICONICTHUMBNAIL)]
  DwmSendIconicThumbnail,
  #[id(WindowsAndMessaging::WM_DWMWINDOWMAXIMIZEDCHANGE)]
  DwmWindowMaximizedChange,
  #[id(WindowsAndMessaging::WM_ENABLE)]
  Enable,
  #[id(WindowsAndMessaging::WM_ENDSESSION)]
  EndSession,
  #[id(WindowsAndMessaging::WM_ENTERIDLE)]
  EnterIdle,
  #[id(WindowsAndMessaging::WM_ENTERMENULOOP)]
  EnterMenuLoop,
  #[id(WindowsAndMessaging::WM_ENTERSIZEMOVE)]
  EnterSizeMove,
  #[id(WindowsAndMessaging::WM_ERASEBKGND)]
  EraseBkgnd,
  #[id(WindowsAndMessaging::WM_EXITMENULOOP)]
  ExitMenuLoop,
  #[id(WindowsAndMessaging::WM_EXITSIZEMOVE)]
  ExitSizeMove,
  #[id(WindowsAndMessaging::WM_FONTCHANGE)]
  FontChange,
  #[id(WindowsAndMessaging::WM_GESTURE)]
  Gesture,
  #[id(WindowsAndMessaging::WM_GESTURENOTIFY)]
  GestureNotify,
  #[id(WindowsAndMessaging::WM_GETDLGCODE)]
  GetDlgCode,
  #[id(WindowsAndMessaging::WM_GETDPISCALEDSIZE)]
  GetDpiScaledSize,
  #[id(WindowsAndMessaging::WM_GETFONT)]
  GetFont,
  #[id(WindowsAndMessaging::WM_GETHOTKEY)]
  GetHotKey,
  #[id(WindowsAndMessaging::WM_GETICON)]
  GetIcon,
  #[id(WindowsAndMessaging::WM_GETMINMAXINFO)]
  GetMinMaxInfo,
  #[id(WindowsAndMessaging::WM_GETOBJECT)]
  GetObject,
  #[id(WindowsAndMessaging::WM_GETTEXT)]
  GetText,
  #[id(WindowsAndMessaging::WM_GETTEXTLENGTH)]
  GetTextLength,
  #[id(WindowsAndMessaging::WM_GETTITLEBARINFOEX)]
  GetTitleBarInfoEx,
  #[id(WindowsAndMessaging::WM_HANDHELDFIRST)]
  HandheldFirst,
  #[id(WindowsAndMessaging::WM_HANDHELDLAST)]
  HandheldLast,
  #[id(WindowsAndMessaging::WM_HELP)]
  Help,
  #[id(WindowsAndMessaging::WM_HOTKEY)]
  HotKey,
  #[id(WindowsAndMessaging::WM_HSCROLL)]
  HScroll,
  #[id(WindowsAndMessaging::WM_HSCROLLCLIPBOARD)]
  HScrollClipboard,
  #[id(WindowsAndMessaging::WM_ICONERASEBKGND)]
  IconEraseBkgnd,
  #[id(WindowsAndMessaging::WM_IME_CHAR)]
  ImeChar,
  #[id(WindowsAndMessaging::WM_IME_COMPOSITION)]
  ImeComposition,
  #[id(WindowsAndMessaging::WM_IME_COMPOSITIONFULL)]
  ImeCompositionFull,
  #[id(WindowsAndMessaging::WM_IME_CONTROL)]
  ImeControl,
  #[id(WindowsAndMessaging::WM_IME_ENDCOMPOSITION)]
  ImeEndComposition,
  #[id(WindowsAndMessaging::WM_IME_KEYDOWN)]
  ImeKeyDown,
  #[id(WindowsAndMessaging::WM_IME_KEYUP)]
  ImeKeyUp,
  #[id(WindowsAndMessaging::WM_IME_NOTIFY)]
  ImeNotify,
  #[id(WindowsAndMessaging::WM_IME_REQUEST)]
  ImeRequest,
  #[id(WindowsAndMessaging::WM_IME_SELECT)]
  ImeSelect,
  #[id(WindowsAndMessaging::WM_IME_SETCONTEXT)]
  ImeSetContext,
  #[id(WindowsAndMessaging::WM_IME_STARTCOMPOSITION)]
  ImeStartComposition,
  #[id(WindowsAndMessaging::WM_INITDIALOG)]
  InitDialog,
  #[id(WindowsAndMessaging::WM_INITMENU)]
  InitMenu,
  #[id(WindowsAndMessaging::WM_INITMENUPOPUP)]
  InitMenuPopup,
  #[id(WindowsAndMessaging::WM_INPUT)]
  Input,
  #[id(WindowsAndMessaging::WM_INPUTLANGCHANGE)]
  InputLangChange,
  #[id(WindowsAndMessaging::WM_INPUTLANGCHANGEREQUEST)]
  InputLangChangeRequest,
  #[id(WindowsAndMessaging::WM_INPUT_DEVICE_CHANGE)]
  InputDeviceChange,
  #[id(WindowsAndMessaging::WM_KEYDOWN)]
  KeyDown,
  #[id(WindowsAndMessaging::WM_KEYUP)]
  KeyUp,
  #[id(WindowsAndMessaging::WM_KILLFOCUS)]
  KillFocus,
  #[id(WindowsAndMessaging::WM_LBUTTONDBLCLK)]
  LButtonDblClk,
  #[id(WindowsAndMessaging::WM_LBUTTONDOWN)]
  LButtonDown,
  #[id(WindowsAndMessaging::WM_LBUTTONUP)]
  LButtonUp,
  #[id(WindowsAndMessaging::WM_MBUTTONDBLCLK)]
  MButtonDblClk,
  #[id(WindowsAndMessaging::WM_MBUTTONDOWN)]
  MButtonDown,
  #[id(WindowsAndMessaging::WM_MBUTTONUP)]
  MButtonUp,
  #[id(WindowsAndMessaging::WM_MDIACTIVATE)]
  MdiActivate,
  #[id(WindowsAndMessaging::WM_MDICASCADE)]
  MdiCascade,
  #[id(WindowsAndMessaging::WM_MDICREATE)]
  MdiCreate,
  #[id(WindowsAndMessaging::WM_MDIDESTROY)]
  MdiDestroy,
  #[id(WindowsAndMessaging::WM_MDIGETACTIVE)]
  MdiGetActive,
  #[id(WindowsAndMessaging::WM_MDIICONARRANGE)]
  MdiIconArrange,
  #[id(WindowsAndMessaging::WM_MDIMAXIMIZE)]
  MdiMaximize,
  #[id(WindowsAndMessaging::WM_MDINEXT)]
  MdiNext,
  #[id(WindowsAndMessaging::WM_MDIREFRESHMENU)]
  MdiRefreshMenu,
  #[id(WindowsAndMessaging::WM_MDIRESTORE)]
  MdiRestore,
  #[id(WindowsAndMessaging::WM_MDISETMENU)]
  MdiSetMenu,
  #[id(WindowsAndMessaging::WM_MDITILE)]
  MdiTile,
  #[id(WindowsAndMessaging::WM_MEASUREITEM)]
  MeasureItem,
  #[id(WindowsAndMessaging::WM_MENUCHAR)]
  MenuChar,
  #[id(WindowsAndMessaging::WM_MENUCOMMAND)]
  MenuCommand,
  #[id(WindowsAndMessaging::WM_MENUDRAG)]
  MenuDrag,
  #[id(WindowsAndMessaging::WM_MENUGETOBJECT)]
  MenuGetObject,
  #[id(WindowsAndMessaging::WM_MENURBUTTONUP)]
  MenuRButtonUp,
  #[id(WindowsAndMessaging::WM_MENUSELECT)]
  MenuSelect,
  #[id(WindowsAndMessaging::WM_MOUSEACTIVATE)]
  MouseActivate,
  #[id(WindowsAndMessaging::WM_MOUSEHWHEEL)]
  MouseHWheel,
  #[id(WindowsAndMessaging::WM_MOUSEMOVE)]
  MouseMove,
  #[id(WindowsAndMessaging::WM_MOUSEWHEEL)]
  MouseWheel,
  #[id(WindowsAndMessaging::WM_MOVE)]
  Move,
  #[id(WindowsAndMessaging::WM_MOVING)]
  Moving,
  #[id(WindowsAndMessaging::WM_NCACTIVATE)]
  NcActivate,
  #[id(WindowsAndMessaging::WM_NCCALCSIZE)]
  NcCalcSize,
  #[id(WindowsAndMessaging::WM_NCCREATE)]
  NcCreate,
  #[id(WindowsAndMessaging::WM_NCDESTROY)]
  NcDestroy,
  #[id(WindowsAndMessaging::WM_NCHITTEST)]
  NcHitTest,
  #[id(WindowsAndMessaging::WM_NCLBUTTONDBLCLK)]
  NcLButtonDblClk,
  #[id(WindowsAndMessaging::WM_NCLBUTTONDOWN)]
  NcLButtonDown,
  #[id(WindowsAndMessaging::WM_NCLBUTTONUP)]
  NcLButtonUp,
  #[id(WindowsAndMessaging::WM_NCMBUTTONDBLCLK)]
  NcMButtonDblClk,
  #[id(WindowsAndMessaging::WM_NCMBUTTONDOWN)]
  NcMButtonDown,
  #[id(WindowsAndMessaging::WM_NCMBUTTONUP)]
  NcMButtonUp,
  #[id(WindowsAndMessaging::WM_NCMOUSEHOVER)]
  NcMouseHover,
  #[id(WindowsAndMessaging::WM_NCMOUSELEAVE)]
  NcMouseLeave,
  #[id(WindowsAndMessaging::WM_NCMOUSEMOVE)]
  NcMouseMove,
  #[id(WindowsAndMessaging::WM_NCPAINT)]
  NcPaint,
  #[id(WindowsAndMessaging::WM_NCPOINTERDOWN)]
  NcPointerDown,
  #[id(WindowsAndMessaging::WM_NCPOINTERUP)]
  NcPointerUp,
  #[id(WindowsAndMessaging::WM_NCPOINTERUPDATE)]
  NcPointerUpdate,
  #[id(WindowsAndMessaging::WM_NCRBUTTONDBLCLK)]
  NcRButtonDblClk,
  #[id(WindowsAndMessaging::WM_NCRBUTTONDOWN)]
  NcRButtonDown,
  #[id(WindowsAndMessaging::WM_NCRBUTTONUP)]
  NcRButtonUp,
  #[id(WindowsAndMessaging::WM_NCXBUTTONDBLCLK)]
  NcXButtonDblClk,
  #[id(WindowsAndMessaging::WM_NCXBUTTONDOWN)]
  NcXButtonDown,
  #[id(WindowsAndMessaging::WM_NCXBUTTONUP)]
  NcXButtonUp,
  #[id(WindowsAndMessaging::WM_NEXTDLGCTL)]
  NextDlgCtl,
  #[id(WindowsAndMessaging::WM_NEXTMENU)]
  NextMenu,
  #[id(WindowsAndMessaging::WM_NOTIFY)]
  Notify,
  #[id(WindowsAndMessaging::WM_NOTIFYFORMAT)]
  NotifyFormat,
  #[id(WindowsAndMessaging::WM_NULL)]
  Null,
  #[id(WindowsAndMessaging::WM_PAINT)]
  Paint,
  #[id(WindowsAndMessaging::WM_PAINTCLIPBOARD)]
  PaintClipboard,
  #[id(WindowsAndMessaging::WM_PAINTICON)]
  PaintIcon,
  #[id(WindowsAndMessaging::WM_PALETTECHANGED)]
  PaletteChanged,
  #[id(WindowsAndMessaging::WM_PALETTEISCHANGING)]
  PaletteIsChanging,
  #[id(WindowsAndMessaging::WM_PARENTNOTIFY)]
  ParentNotify,
  #[id(WindowsAndMessaging::WM_PASTE)]
  Paste,
  #[id(WindowsAndMessaging::WM_PENWINFIRST)]
  PenWinFirst,
  #[id(WindowsAndMessaging::WM_PENWINLAST)]
  PenWinLast,
  #[id(WindowsAndMessaging::WM_POINTERACTIVATE)]
  PointerActivate,
  #[id(WindowsAndMessaging::WM_POINTERCAPTURECHANGED)]
  PointerCaptureChanged,
  #[id(WindowsAndMessaging::WM_POINTERDEVICECHANGE)]
  PointerDeviceChange,
  #[id(WindowsAndMessaging::WM_POINTERDEVICEINRANGE)]
  PointerDeviceInRange,
  #[id(WindowsAndMessaging::WM_POINTERDEVICEOUTOFRANGE)]
  PointerDeviceOutOfRange,
  #[id(WindowsAndMessaging::WM_POINTERDOWN)]
  PointerDown,
  #[id(WindowsAndMessaging::WM_POINTERENTER)]
  PointerEnter,
  #[id(WindowsAndMessaging::WM_POINTERHWHEEL)]
  PointerHWheel,
  #[id(WindowsAndMessaging::WM_POINTERLEAVE)]
  PointerLeave,
  #[id(WindowsAndMessaging::WM_POINTERROUTEDAWAY)]
  PointerRoutedAway,
  #[id(WindowsAndMessaging::WM_POINTERROUTEDRELEASED)]
  PointerRoutedReleased,
  #[id(WindowsAndMessaging::WM_POINTERROUTEDTO)]
  PointerRoutedTo,
  #[id(WindowsAndMessaging::WM_POINTERUP)]
  PointerUp,
  #[id(WindowsAndMessaging::WM_POINTERUPDATE)]
  PointerUpdate,
  #[id(WindowsAndMessaging::WM_POINTERWHEEL)]
  PointerWheel,
  #[id(WindowsAndMessaging::WM_POWER)]
  Power,
  #[id(WindowsAndMessaging::WM_POWERBROADCAST)]
  PowerBroadcast,
  #[id(WindowsAndMessaging::WM_PRINT)]
  Print,
  #[id(WindowsAndMessaging::WM_PRINTCLIENT)]
  PrintClient,
  #[id(WindowsAndMessaging::WM_QUERYDRAGICON)]
  QueryDragIcon,
  #[id(WindowsAndMessaging::WM_QUERYENDSESSION)]
  QueryEndSession,
  #[id(WindowsAndMessaging::WM_QUERYNEWPALETTE)]
  QueryNewPalette,
  #[id(WindowsAndMessaging::WM_QUERYOPEN)]
  QueryOpen,
  #[id(WindowsAndMessaging::WM_QUERYUISTATE)]
  QueryUiState,
  #[id(WindowsAndMessaging::WM_QUEUESYNC)]
  QueueSync,
  #[id(WindowsAndMessaging::WM_QUIT)]
  Quit,
  #[id(WindowsAndMessaging::WM_RBUTTONDBLCLK)]
  RButtonDblClk,
  #[id(WindowsAndMessaging::WM_RBUTTONDOWN)]
  RButtonDown,
  #[id(WindowsAndMessaging::WM_RBUTTONUP)]
  RButtonUp,
  #[id(WindowsAndMessaging::WM_RENDERALLFORMATS)]
  RenderAllFormats,
  #[id(WindowsAndMessaging::WM_RENDERFORMAT)]
  RenderFormat,
  #[id(WindowsAndMessaging::WM_SETCURSOR)]
  SetCursor,
  #[id(WindowsAndMessaging::WM_SETFOCUS)]
  SetFocus,
  #[id(WindowsAndMessaging::WM_SETFONT)]
  SetFont,
  #[id(WindowsAndMessaging::WM_SETHOTKEY)]
  SetHotKey,
  #[id(WindowsAndMessaging::WM_SETICON)]
  SetIcon,
  #[id(WindowsAndMessaging::WM_SETREDRAW)]
  SetRedraw,
  #[id(WindowsAndMessaging::WM_SETTEXT)]
  SetText,
  #[id(WindowsAndMessaging::WM_SETTINGCHANGE)]
  SettingChange,
  #[id(WindowsAndMessaging::WM_SHOWWINDOW)]
  ShowWindow,
  #[id(WindowsAndMessaging::WM_SIZE)]
  Size,
  #[id(WindowsAndMessaging::WM_SIZECLIPBOARD)]
  SizeClipboard,
  #[id(WindowsAndMessaging::WM_SIZING)]
  Sizing,
  #[id(WindowsAndMessaging::WM_SPOOLERSTATUS)]
  SpoolerStatus,
  #[id(WindowsAndMessaging::WM_STYLECHANGED)]
  StyleChanged,
  #[id(WindowsAndMessaging::WM_STYLECHANGING)]
  StyleChanging,
  #[id(WindowsAndMessaging::WM_SYNCPAINT)]
  SyncPaint,
  #[id(WindowsAndMessaging::WM_SYSCHAR)]
  SysChar,
  #[id(WindowsAndMessaging::WM_SYSCOLORCHANGE)]
  SysColorChange,
  #[id(WindowsAndMessaging::WM_SYSCOMMAND)]
  SysCommand,
  #[id(WindowsAndMessaging::WM_SYSDEADCHAR)]
  SysDeadChar,
  #[id(WindowsAndMessaging::WM_SYSKEYDOWN)]
  SysKeyDown,
  #[id(WindowsAndMessaging::WM_SYSKEYUP)]
  SysKeyUp,
  #[id(WindowsAndMessaging::WM_TABLET_FIRST)]
  TabletFirst,
  #[id(WindowsAndMessaging::WM_TABLET_LAST)]
  TabletLast,
  #[id(WindowsAndMessaging::WM_TCARD)]
  TCard,
  #[id(WindowsAndMessaging::WM_THEMECHANGED)]
  ThemeChanged,
  #[id(WindowsAndMessaging::WM_TIMECHANGE)]
  TimeChange,
  #[id(WindowsAndMessaging::WM_TIMER)]
  Timer,
  #[id(WindowsAndMessaging::WM_TOOLTIPDISMISS)]
  TooltipDismiss,
  #[id(WindowsAndMessaging::WM_TOUCH)]
  Touch,
  #[id(WindowsAndMessaging::WM_TOUCHHITTESTING)]
  TouchHitTesting,
  #[id(WindowsAndMessaging::WM_UNDO)]
  Undo,
  #[id(WindowsAndMessaging::WM_UNICHAR)]
  UniChar,
  #[id(WindowsAndMessaging::WM_UNINITMENUPOPUP)]
  UninitMenuPopup,
  #[id(WindowsAndMessaging::WM_UPDATEUISTATE)]
  UpdateUiState,
  #[id(WindowsAndMessaging::WM_USER)]
  User,
  #[id(WindowsAndMessaging::WM_USERCHANGED)]
  UserChanged,
  #[id(WindowsAndMessaging::WM_VKEYTOITEM)]
  VKeyToItem,
  #[id(WindowsAndMessaging::WM_VSCROLL)]
  VScroll,
  #[id(WindowsAndMessaging::WM_VSCROLLCLIPBOARD)]
  VScrollClipboard,
  #[id(WindowsAndMessaging::WM_WINDOWPOSCHANGED)]
  WindowPosChanged,
  #[id(WindowsAndMessaging::WM_WINDOWPOSCHANGING)]
  WindowPosChanging,
  #[id(WindowsAndMessaging::WM_WTSSESSION_CHANGE)]
  WtsSessionChange,
  #[id(WindowsAndMessaging::WM_XBUTTONDBLCLK)]
  XButtonDblClk,
  #[id(WindowsAndMessaging::WM_XBUTTONDOWN)]
  XButtonDown,
  #[id(WindowsAndMessaging::WM_XBUTTONUP)]
  XButtonUp,
}
